var works = [{
        categoryId: 2,
        categoryName: "ui-design",
        title: "Daily UI Challenge",
        year: "On going",
        category: "UI Design, Front-End Development",
        url: "/dailyui",
        thumb: "images/works/dailyui/dailyui_00.jpg",
        fullClass: true,
        featured: true,
    },
    {
        categoryId: 2,
        categoryName: "ui-design",
        title: "Quinta da Valeira Website",
        year: "2019",
        category: "UI Design, Front-End Development",
        thumb: "images/works/valeirawebsite/valeirawebsite_01.jpg",
        url: "works/valeirawebsite.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 2,
        categoryName: "ui-design",
        title: "Weather App",
        year: "2019",
        category: "UI Design",
        thumb: "images/works/weatherapp/weatherapp_01.jpg",
        url: "works/weatherapp.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 3,
        categoryName: "packaging",
        title: "Quinta da Valeira",
        year: "2018",
        category: "Label Design & Branding",
        thumb: "images/works/valeira/valeira_09.jpg",
        url: "works/valeira.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 3,
        categoryName: "packaging",
        title: "Quevedo Advent Calendar 2017 / 2018",
        year: "2017-2018",
        category: "Packaging, Graphic Design & Illustration",
        thumb: "images/works/quevedoadvent2018/quevedo_advent2018_03.jpg",
        url: "works/quevedoadvent2018.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 3,
        categoryName: "packaging",
        title: "Quevedo Vintage",
        year: "2017",
        category: "Label Design",
        thumb: "images/works/quevedovintage/quevedo_vintage_01.jpg",
        url: "works/quevedoadvent2018.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 1,
        categoryName: "graphic",
        title: "10",
        year: "2017",
        category: "Graphic Composition",
        thumb: "images/works/10/10_01.jpg",
        url: "works/10.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 1,
        categoryName: "graphic",
        title: "Closer",
        year: "2017",
        category: "Type Poster",
        thumb: "images/works/closerposter/closer_04.jpg",
        url: "works/closerposter.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 1,
        categoryName: "graphic",
        title: "Finca Leyenda Plata - Logo Proposal",
        year: "2016",
        category: "Logo Design",
        thumb: "images/works/fincaleyendaplata/finca_01.jpg",
        url: "works/fincaleyendaplata.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 1,
        categoryName: "graphic",
        title: "Viñedos Ruta Sagrada - Logo Proposal",
        year: "2016",
        category: "Logo Design",
        thumb: "images/works/vinedosrutasagrada/vinedos_00.png",
        url: "works/vinedosrutasagrada.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 3,
        categoryName: "packaging",
        title: "Quevedo Douro Wines rebrand - Q Grande Reserva",
        year: "2016",
        category: "Label Design",
        thumb: "images/works/quevedogreserve/quevedogreserve_04.jpg",
        url: "works/quevedogreserve.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 3,
        categoryName: "packaging",
        title: "Quevedo Douro Wines rebrand",
        year: "2016",
        category: "Label Design",
        thumb: "images/works/quevedodouro/quevedodouro_06.jpg",
        url: "works/quevedodouro.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 5,
        categoryName: "illustration",
        title: "Darwin Vineyards Chalk Illustrations",
        year: "2016",
        category: "Illustration",
        thumb: "images/works/chalkillustrations/chalkillustration_01.jpg",
        url: "works/chalkillustrations.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 5,
        categoryName: "illustration",
        title: "Prowein 2017 Poster",
        year: "2016",
        category: "Illustration",
        thumb: "images/works/prowein2017/prowein2017_03.jpg",
        url: "works/prowein2017.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 3,
        categoryName: "packaging",
        title: "Quinta da Trovisca rebrand",
        year: "2016",
        category: "Label Design",
        thumb: "images/works/trovisca/trovisca_03.jpg",
        url: "works/trovisca.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 5,
        categoryName: "illustration",
        title: "Darwin Vineyards’ Christmas bottle",
        year: "2015",
        category: "Illustration",
        thumb: "images/works/bottleillustration/bottleillustration_01.jpg",
        url: "works/bottleillustration.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 4,
        categoryName: "editorial",
        title: "Internship report",
        year: "2015",
        category: "Editorial Design",
        thumb: "images/works/tese/tese_02.jpg",
        url: "works/tese.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 1,
        categoryName: "graphic",
        title: "Colönia Font",
        year: "2015",
        category: "Type Design",
        thumb: "images/works/coloniafont/colonia_font_07.jpg",
        url: "works/coloniafont.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 4,
        categoryName: "editorial",
        title: "Uma Avenida, Três Vidas",
        year: "2014",
        category: "Editorial Design",
        thumb: "images/works/umaavenida/umaavenida_02.jpg",
        url: "works/umaavenida.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 4,
        categoryName: "editorial",
        title: "Versus: Tim Burton and Woody Allen",
        year: "2014",
        category: "Editorial Design",
        thumb: "images/works/timvswoody/covers.jpg",
        url: "works/tellmeaboutit.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 4,
        categoryName: "editorial",
        title: "Tell Me about It: Stories of Songwriters",
        year: "2014",
        category: "Editorial Design",
        thumb: "images/works/tellmeaboutit/tellmeaboutit_01.jpg",
        url: "works/tellmeaboutit.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 5,
        categoryName: "illustration",
        title: "Happy Songs about Sad Things",
        year: "2013",
        category: "Illustration",
        thumb: "images/works/happysongs/happysongs_01.jpg",
        url: "works/happysongs.html",
        fullClass: false,
        featured: true,
    },
    {
        categoryId: 1,
        categoryName: "graphic",
        title: "1# Type",
        year: "2013",
        category: "Type Design",
        thumb: "images/works/type/type_06.jpg",
        url: "works/type.html",
        fullClass: false,
        featured: true,
    }
];

/* 
1 - graphic
2 - ui
3 - packaing
4 - editorial
5 - illustration
*/
var worksContainer = document.querySelector('.container-works'),
    worksContainerHome = document.querySelector('.container-home');


for (let i = 0; i < works.length; i++) {
    const {
        categoryId,
        title,
        year,
        category,
        thumb,
        url,
        fullClass,
        featured,
        categoryName,
    } = works[i];


    var template = `<a id ="${categoryName}" data-id="${categoryId}" class="work ${fullClass ? "full" : ""}" href="${url}">
    <div class="image">
        <div class="img" style="background-image: url(${thumb})"></div>
        <p class=" overlay-title">${title}</p>
        <p class="overlay-text">${year} / ${category}</p>
    </div>
</a>`;

    if (worksContainer) {
        worksContainer.insertAdjacentHTML('beforeend', template);
    } else if (worksContainerHome && featured) {

        worksContainerHome.insertAdjacentHTML('beforeend', template);
    }


}